MODULE EXAMPLEDLM
DESCRIPTION Several examples of simple DLM code for easier development
VERSION 1.0
SOURCE RICHIE ZENG


FUNCTION EX_HELLO_FUNC 0 1
PROCEDURE EX_HELLO_PROC 0 1
FUNCTION EX_SIMPLE_INT 1 1
FUNCTION EX_SIMPLE_UINT 1 1

PROCEDURE EX_INPLACEARR 1 1
